# Generated by Django 4.0 on 2022-07-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_for_bid', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='listing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.auctionlisting'),
        ),
    ]
