# Generated by Django 4.0 on 2022-07-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_listing_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('listing_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_for', to='auctions.auctionlisting')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='auctions.user')),
            ],
        ),
    ]
