# Generated by Django 4.0 on 2022-07-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_for', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='auctions.user'),
        ),
    ]
